name: Build Latex Docker Image

on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - Dockerfile
  #     - .github/workflows/build.yaml
  workflow_call:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Log in to the Github Container registry'
        uses: 'docker/login-action@v3'
        with:
          registry: 'ghcr.io'
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Generate a Release Tag'
        working-directory: ${{ env.ADGUARDHOME_BUILD_PATH }}
        id: build-version
        run: |
          # latest_version=$( git -C "./" describe HEAD | sed 's|\(.*\)-.*|\1|' )
          # latest_version=$( git -C "./" describe HEAD --abbrev=0 )
          # echo "release_tag=${latest_version}" >> $GITHUB_ENV
          # echo "release_name=${latest_version}" >> $GITHUB_ENV
          echo "build_date=$( date -u +'%Y-%m-%dT%H:%M:%SZ' )" >> $GITHUB_ENV

      - name: 'Set up Docker Buildx'
        uses: 'docker/setup-buildx-action@v3'

      - name: 'Build & Publish Docker Image'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          outputs: type=image
          platforms: linux/amd64, linux/arm64
          # build-args: |
              # NONE=${{ env.NONE }}
          labels: |
            maintainer=${{ github.actor }}
            org.opencontainers.image.created=${{ env.build_date }}
            org.opencontainers.image.description=LedFx Docker
            org.opencontainers.image.licenses=GPL-3.0
            org.opencontainers.image.source=https://github/${{ github.repository }}
            org.opencontainers.image.title=Docker Latex
            org.opencontainers.image.url=https://github/${{ github.repository }}
            org.opencontainers.image.version=1.0
          tags: |
            ghcr.io/${{ github.repository }}:latest
